# Generated by Django 6.1 on 2026-08-23 04:28

import scanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsession',
            name='error_message',
        ),
        migrations.AddField(
            model_name='scanimage',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=scanner.models.scan_thumb_path),
        ),
        migrations.AlterField(
            model_name='importsession',
            name='status',
            field=models.CharField(choices=[('capturing', 'Capturando fotos'), ('processing', 'Procesando'), ('ready', 'Lista para validar'), ('closed', 'Cerrada')], default='capturing', max_length=20),
        ),
    ]
